# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78f8e4b76ef8df14429828fc3df0f86927a02f22cfdc764445d4bc67c43e01b5d962b11512eda8e32d689936fdba9415a1786a065eedc5bd3d7c3b7b4b1f57e3

test:
  secret_key_base: ccac0132beeb821be1c96797791f3cf86da9905540aead2105686be07ae14919264d87c9e89fda7d3bbce7d7ead5ebcdb0cb0070e4d25e9300fbc4303d69fd92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
